name: Backup Firestore DateRecorder

on:
    #schedule:
    #    - cron: "57 21 * * *"
    push:
        branches:
            - master
jobs:
    backup:
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "hola mundo, a y 25"
